# Spring Boot configuration
spring:
  application:
    name: ticket
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5433/ticket_db
    username: postgres
    password: postgres

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  # Cassandra
  data:
    cassandra:
      schema-action: none
      keyspace-name: ec_ks
      contact-points: 127.0.0.1
      local-datacenter: datacenter1
      port: 9042
      ssl: false
      connection:
        connect-timeout: 5s


# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 8082
  error:
    include-binding-errors: always
    include-message: always

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# API Docs
springdoc:
  api-docs:
    path: /api/v2/ticket/api-docs