# Spring Boot configuration
spring:
  application:
    name: notification

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest

  # Redis
  redis:
    host: localhost
    port: 6379

  # Mailer
  mail:
    host: smtp.gmail.com
    port: 587
    username: eurhainez@gmail.com
    password: touqamftsvurcwaj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info

# Server configuration
server:
  port: 8085
  error:
    include-binding-errors: always
    include-message: always

# Eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

userprofile:
  service_url: http://localhost:8084

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always