spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8443/realms/TSM%20Realm
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: eureka
          uri: http://${eureka.instance.hostname}:8761
          predicates:
          - Path=/eureka/web
          filters:
          - SetPath=/
        - id: eureka-static
          uri: http://${eureka.instance.hostname}:8761
          predicates:
          - Path=/eureka/**

        - id: account
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v3/accounts/**
        - id: event-query
          uri: lb://EVENT-QUERY-SERVICE
          predicates:
          - Path=/api/v3/events/**
          - Method=GET
        - id: event-command
          uri: lb://EVENT-COMMAND-SERVICE
          predicates:
          - Path=/api/v3/events/**
          - Method=POST, PUT, PATCH, DELETE
        - id: ticket
          uri: lb://TICKET-SERVICE
          predicates:
          - Path=/api/v3/event/**, /api/v3/tickets/**, /api/v3/purchases/**

        - id: account-swagger
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/swagger-ui**, /account-service/api-docs
            - Method=GET
        - id: event-query-swagger
          uri: lb://EVENT-QUERY-SERVICE
          predicates:
            - Path=/event-query-service/swagger-ui**, /event-query-service/api-docs
            - Method=GET
        - id: event-command-swagger
          uri: lb://EVENT-COMMAND-SERVICE
          predicates:
          - Path=/event-command-service/swagger-ui**, /event-command-service/api-docs
          - Method=GET
        - id: ticket-swagger
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket-service/swagger-ui**, /ticket-service/api-docs
            - Method=GET

# Logger configuration
logging:
  pattern:
    console: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 9000
  error:
    include-binding-errors: always
    include-message: always

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

# Monitoring
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
