spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: eureka
          uri: http://localhost:8761
          predicates:
          - Path=/eureka/web
          filters:
          - SetPath=/
        - id: eureka-static
          uri: http://localhost:8761
          predicates:
          - Path=/eureka/**

        - id: event-management
          uri: lb://EVENT-MGMT
          predicates:
          - Path=/api/v2/event/**

        - id: ticket-management
          uri: lb://TICKET-MGMT
          predicates:
          - Path=/api/v2/ticket/**

        - id: swagger-ui-event-mgmt
          uri: lb://EVENT-MGMT/api/v2/event/swagger/ui
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**,/swagger-ui.html, /v2/api-docs,/webjars/**,/view/**
          filters:
            - RewritePath=/api/v2/event/(?<path>.*), /$\{path}

        - id: swagger-ui-ticket-mgmt
          uri: lb://TICKET-MGMT/api/v2/ticket/swagger/ui
          predicates:
            - Path=/swagger-ui/**,/swagger-resources/**, /swagger-ui.html, /v2/api-docs,/webjars/**,/view/**
          filters:
            - RewritePath=/api/v2/ticket/(?<path>.*), /$\{path}


# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

# Server configuration
server:
  port: 9000
  error:
    include-binding-errors: always
    include-message: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


