spring:
  application:
    name: event-indexer

  # Kafka
  kafka:
    bootstrap-servers: '[::1]:9092'
    consumer:
      auto-offset-reset: earliest

# ES config
elasticsearch:
  hostname: localhost
  server: http://${elasticsearch.hostname}:9200
  user: event_indexer
  pass: elastic

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

# Server configuration
server:
  port: 8086
  error:
    include-binding-errors: always
    include-message: always

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    elasticsearch:
      enabled: false

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org:
      springframework: info